# 配置文件示例
# 基础配置
agent:

  # 项目名称，用于区分项目
  project: ""

  # 接受数据地址
  metrics_url: ""

# 是否开启采集,true为开启，false为不开启
metrics:

  # 是否开启采集ssl证书到期时间
  ssl:
    enable: false

  # 是否开启Nginx服务器信息采集
  nginx:
    enable: false

  # 是否开启harbor服务信息采集
  harbor:
    enable: false

  # 是否开启采集k8s集群pod资源信息
  k8s:
    enable: false
    # 开启之后需要填入路径，如果是当前路径直接写admin.conf,如果不是就写绝对路径
    config_path: ""

# 加密盐，数据加密传输
encrypted: ""